# action.yml
name: 'Hello World'
on: [workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: |
          ./.github/test.sh >| README.md
          echo README.md
