# action.yml
env:
  HACKMD_CLI_TOKEN: secrets.HACKMD_CLI_TOKEN
name: 'Hello World'
on: [workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: |
          ./.github/test.sh >| README.md
          cat README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: 週1
          branch: minutes-for-pull-request
          base: minutes
          delete-branch: true
