# action.yml
name: 'Hello World'
on: [push]
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g @hackmd/hackmd-cli