# action.yml
env:
  HACKMD_CLI_TOKEN: secrets.HACKMD_CLI_TOKEN
name: '【定期】議事録プッシュ'
on:
  schedule:
    # アクセスが集中しそうな時間帯を避けました．
    # 時刻は適当です．
    - cron: '37 17 * * 0'
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: |
          curl "${{secrets.HACKMD_MINUTES_URL}}" -H "Authorization: Bearer ${{secrets.HACKMD_CLI_TOKEN}}" | jq -r '.content'  >| README.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: 週一の議事録
          branch-suffix: timestamp
          base: minutes
          delete-branch: true
